import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1725471974847 implements MigrationInterface {
    name = 'Default1725471974847'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "VIDEOS" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "TITLE" varchar2(255) NOT NULL, "DESCRICAO" varchar2(255) NOT NULL, "PUBLICLINK" varchar2(255) NOT NULL, CONSTRAINT "PK_0cb2126675b2781186af888578e" PRIMARY KEY ("UUID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "VIDEOS"`);
    }

}
