import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1725481999567 implements MigrationInterface {
    name = 'Default1725481999567'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "USUARIOS" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "USERNAME" varchar2(255) NOT NULL, "PASSWORD" varchar2(255) NOT NULL, CONSTRAINT "PK_0d863bf429e491a2f11ba3d51f6" PRIMARY KEY ("UUID"))`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`DROP TABLE "USUARIOS"`);
    }

}
