import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1726261671073 implements MigrationInterface {
    name = 'Default1726261671073'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "trending" ("id" number GENERATED BY DEFAULT AS IDENTITY, "uuid" varchar2(255), "message" varchar2(255), "base64" clob, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "usuario_id" number, CONSTRAINT "PK_67fa365dcd46bd65397a019bec4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("id" number GENERATED BY DEFAULT AS IDENTITY, "uuid" varchar2(255), "name" varchar2(255) NOT NULL, "base64" clob, "username" varchar2(255) NOT NULL, "password" varchar2(255) NOT NULL, CONSTRAINT "PK_d7281c63c176e152e4c531594a8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "trending" ADD CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "trending" DROP CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "trending"`);
    }

}
