import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1726185055346 implements MigrationInterface {
    name = 'Default1726185055346'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "thoughts" ("uuid" number GENERATED BY DEFAULT AS IDENTITY, "message" varchar2(255) NOT NULL, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "usuario_id" number, CONSTRAINT "PK_8c567cece2efcb84eb95d5fcff1" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("uuid" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "username" varchar2(255) NOT NULL, "password" varchar2(255) NOT NULL, CONSTRAINT "PK_310d8b14bec46dd9e321d4a1b7c" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "videos" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "title" varchar2(255) NOT NULL, "description" varchar2(255) NOT NULL, "path" varchar2(255) NOT NULL, "usuario_id" number, CONSTRAINT "PK_fe32ab520a208b9d9a860acbf89" PRIMARY KEY ("UUID"))`);
        await queryRunner.query(`ALTER TABLE "thoughts" ADD CONSTRAINT "FK_446486573828682fbc11d772e9f" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("uuid")`);
        await queryRunner.query(`ALTER TABLE "videos" ADD CONSTRAINT "FK_691eb613faba435ff2ae9ddefb7" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("uuid")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "videos" DROP CONSTRAINT "FK_691eb613faba435ff2ae9ddefb7"`);
        await queryRunner.query(`ALTER TABLE "thoughts" DROP CONSTRAINT "FK_446486573828682fbc11d772e9f"`);
        await queryRunner.query(`DROP TABLE "videos"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "thoughts"`);
    }

}
