import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1726248158613 implements MigrationInterface {
    name = 'Default1726248158613'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "trending" ("uuid" number GENERATED BY DEFAULT AS IDENTITY, "message" varchar2(255), "base64" clob, "share" clob, "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "usuario_id" number, CONSTRAINT "PK_b0ea5e8c33f5834d147cfcbc342" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "usuarios" ("uuid" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "username" varchar2(255) NOT NULL, "password" varchar2(255) NOT NULL, CONSTRAINT "PK_310d8b14bec46dd9e321d4a1b7c" PRIMARY KEY ("uuid"))`);
        await queryRunner.query(`CREATE TABLE "videos" ("UUID" number GENERATED BY DEFAULT AS IDENTITY, "title" varchar2(255) NOT NULL, "description" varchar2(255) NOT NULL, "path" varchar2(255) NOT NULL, "usuario_id" number, CONSTRAINT "PK_fe32ab520a208b9d9a860acbf89" PRIMARY KEY ("UUID"))`);
        await queryRunner.query(`ALTER TABLE "trending" ADD CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("uuid")`);
        await queryRunner.query(`ALTER TABLE "videos" ADD CONSTRAINT "FK_691eb613faba435ff2ae9ddefb7" FOREIGN KEY ("usuario_id") REFERENCES "usuarios" ("uuid")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "videos" DROP CONSTRAINT "FK_691eb613faba435ff2ae9ddefb7"`);
        await queryRunner.query(`ALTER TABLE "trending" DROP CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df"`);
        await queryRunner.query(`DROP TABLE "videos"`);
        await queryRunner.query(`DROP TABLE "usuarios"`);
        await queryRunner.query(`DROP TABLE "trending"`);
    }

}
