import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1726941525856 implements MigrationInterface {
    name = 'Default1726941525856'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "trending" ("id" number GENERATED BY DEFAULT AS IDENTITY, "uuid" varchar2(255), "message" varchar2(255), "uri" varchar2(255), "link" varchar2(255), "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "usuarioId" number, CONSTRAINT "PK_67fa365dcd46bd65397a019bec4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "imagen" ("id" number GENERATED BY DEFAULT AS IDENTITY, "uuid" number NOT NULL, "name" varchar2(255) NOT NULL, "base64" clob NOT NULL, "profileId" number, "trendingId" number, CONSTRAINT "REL_04a03b7c9ef376f866fb6da03b" UNIQUE ("profileId"), CONSTRAINT "REL_b0e9b82a9c40f8012f8e97beb9" UNIQUE ("trendingId"), CONSTRAINT "PK_c9838d52bca36e9244bcb95bee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profile" ("id" number GENERATED BY DEFAULT AS IDENTITY, "uuid" number NOT NULL, "name" varchar2(100) NOT NULL, "email" varchar2(100) NOT NULL, "biography" varchar2(100), "usuarioId" number, CONSTRAINT "REL_15aa9e08b5c9d0e78e8d432994" UNIQUE ("usuarioId"), CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id" number GENERATED BY DEFAULT AS IDENTITY, "username" varchar2(255) NOT NULL, "password" varchar2(255) NOT NULL, "profileId" number, CONSTRAINT "REL_760bd7f757ec1358f55aa2bfa9" UNIQUE ("profileId"), CONSTRAINT "PK_a56c58e5cabaa04fb2c98d2d7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "trending" ADD CONSTRAINT "FK_6512c2208d4b66879a8739b145d" FOREIGN KEY ("usuarioId") REFERENCES "usuario" ("id")`);
        await queryRunner.query(`ALTER TABLE "imagen" ADD CONSTRAINT "FK_04a03b7c9ef376f866fb6da03ba" FOREIGN KEY ("profileId") REFERENCES "profile" ("id")`);
        await queryRunner.query(`ALTER TABLE "imagen" ADD CONSTRAINT "FK_b0e9b82a9c40f8012f8e97beb9c" FOREIGN KEY ("trendingId") REFERENCES "trending" ("id")`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_15aa9e08b5c9d0e78e8d4329942" FOREIGN KEY ("usuarioId") REFERENCES "usuario" ("id")`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_760bd7f757ec1358f55aa2bfa9e" FOREIGN KEY ("profileId") REFERENCES "profile" ("id") ON DELETE CASCADE`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_760bd7f757ec1358f55aa2bfa9e"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_15aa9e08b5c9d0e78e8d4329942"`);
        await queryRunner.query(`ALTER TABLE "imagen" DROP CONSTRAINT "FK_b0e9b82a9c40f8012f8e97beb9c"`);
        await queryRunner.query(`ALTER TABLE "imagen" DROP CONSTRAINT "FK_04a03b7c9ef376f866fb6da03ba"`);
        await queryRunner.query(`ALTER TABLE "trending" DROP CONSTRAINT "FK_6512c2208d4b66879a8739b145d"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "profile"`);
        await queryRunner.query(`DROP TABLE "imagen"`);
        await queryRunner.query(`DROP TABLE "trending"`);
    }

}
