import { MigrationInterface, QueryRunner } from "typeorm";

export class Default1727188313881 implements MigrationInterface {
    name = 'Default1727188313881'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "profile" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(100) NOT NULL, "email" varchar2(100) NOT NULL, "biography" varchar2(100), "usuario" number, "usuario_id" number, CONSTRAINT "REL_55786b3b056a0e257de0544c0a" UNIQUE ("usuario_id"), CONSTRAINT "PK_3dd8bfc97e4a77c70971591bdcb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "imagen" ("id" number GENERATED BY DEFAULT AS IDENTITY, "name" varchar2(255) NOT NULL, "base64" clob NOT NULL, "usuario" number, "trending" number, "usuario_id" number, CONSTRAINT "REL_ea228b85fd2cc829837a2ac4bf" UNIQUE ("usuario_id"), CONSTRAINT "PK_c9838d52bca36e9244bcb95bee6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trending" ("id" number GENERATED BY DEFAULT AS IDENTITY, "message" varchar2(255), "uri" varchar2(255), "link" varchar2(255), "created" timestamp DEFAULT CURRENT_TIMESTAMP NOT NULL, "usuario" number NOT NULL, "usuario_id" number, CONSTRAINT "PK_67fa365dcd46bd65397a019bec4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "usuario" ("id" number GENERATED BY DEFAULT AS IDENTITY, "username" varchar2(255) NOT NULL, "password" varchar2(255) NOT NULL, "profile_id" number, CONSTRAINT "UQ_6ccff37176a6978449a99c82e10" UNIQUE ("username"), CONSTRAINT "REL_c924fd2c82294ce7c395644bdc" UNIQUE ("profile_id"), CONSTRAINT "PK_a56c58e5cabaa04fb2c98d2d7e2" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "trending_imagens" ("trending_id" number NOT NULL, "imagens_id" number NOT NULL, CONSTRAINT "PK_a2b695d153f63c353c3843320b9" PRIMARY KEY ("trending_id", "imagens_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1332b7a29e3eb4a0854bbde148" ON "trending_imagens" ("trending_id")`);
        await queryRunner.query(`CREATE INDEX "IDX_3c5bb988c4ed92aa119be6c200" ON "trending_imagens" ("imagens_id")`);
        await queryRunner.query(`ALTER TABLE "profile" ADD CONSTRAINT "FK_55786b3b056a0e257de0544c0a8" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id")`);
        await queryRunner.query(`ALTER TABLE "imagen" ADD CONSTRAINT "FK_ea228b85fd2cc829837a2ac4bfe" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id")`);
        await queryRunner.query(`ALTER TABLE "trending" ADD CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df" FOREIGN KEY ("usuario_id") REFERENCES "usuario" ("id")`);
        await queryRunner.query(`ALTER TABLE "usuario" ADD CONSTRAINT "FK_c924fd2c82294ce7c395644bdce" FOREIGN KEY ("profile_id") REFERENCES "profile" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "trending_imagens" ADD CONSTRAINT "FK_1332b7a29e3eb4a0854bbde1483" FOREIGN KEY ("trending_id") REFERENCES "trending" ("id") ON DELETE CASCADE`);
        await queryRunner.query(`ALTER TABLE "trending_imagens" ADD CONSTRAINT "FK_3c5bb988c4ed92aa119be6c200c" FOREIGN KEY ("imagens_id") REFERENCES "imagen" ("id")`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "trending_imagens" DROP CONSTRAINT "FK_3c5bb988c4ed92aa119be6c200c"`);
        await queryRunner.query(`ALTER TABLE "trending_imagens" DROP CONSTRAINT "FK_1332b7a29e3eb4a0854bbde1483"`);
        await queryRunner.query(`ALTER TABLE "usuario" DROP CONSTRAINT "FK_c924fd2c82294ce7c395644bdce"`);
        await queryRunner.query(`ALTER TABLE "trending" DROP CONSTRAINT "FK_b79e5990b0ecdb3b5eccc67c0df"`);
        await queryRunner.query(`ALTER TABLE "imagen" DROP CONSTRAINT "FK_ea228b85fd2cc829837a2ac4bfe"`);
        await queryRunner.query(`ALTER TABLE "profile" DROP CONSTRAINT "FK_55786b3b056a0e257de0544c0a8"`);
        await queryRunner.query(`DROP INDEX "IDX_3c5bb988c4ed92aa119be6c200"`);
        await queryRunner.query(`DROP INDEX "IDX_1332b7a29e3eb4a0854bbde148"`);
        await queryRunner.query(`DROP TABLE "trending_imagens"`);
        await queryRunner.query(`DROP TABLE "usuario"`);
        await queryRunner.query(`DROP TABLE "trending"`);
        await queryRunner.query(`DROP TABLE "imagen"`);
        await queryRunner.query(`DROP TABLE "profile"`);
    }

}
